package gophx

// Event ...
type Event string

const (
	// CLOSE ...
	CLOSE Event = "phx_close"
	// ERROR ...
	ERROR Event = "phx_error"
	// JOIN ...
	JOIN Event = "phx_join"
	// REPLY ...
	REPLY Event = "phx_reply"
	// LEAVE ...
	LEAVE Event = "phx_leave"
	// HEARTBEAT ...
	HEARTBEAT Event = "phx_ping"
	// MSG ...
	MSG Event = "new_msg"
)
